env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

overrides: []

parser: "@typescript-eslint/parser"

plugins: ["@typescript-eslint"]

parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: latest
  sourceType: module

rules:
  no-tabs: off
  indent: ["error", "tab"]

ignorePatterns:
  - webpack.config.js

root: true
