[package]
name = "distringo-fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = "4.2.7"
reqwest = "0.11.18"
suppaftp = "5.1.1"
tokio = { version = "1.28.1", features = ["macros", "rt", "rt-multi-thread", "tracing", "io-std"] }
tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "tracing-log"] }
