[package]
name = "distringo-fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.10"
reqwest = "0.11.14"
suppaftp = "5.1.0"
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["fmt"] }
