version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 99
  commit-message: { prefix: "" }
  reviewers: [ rye ]
  assignees: [ rye ]
  allow:
  - dependency-type: direct
  - dependency-type: indirect

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
  commit-message: { prefix: "" }
  reviewers: [ rye ]
  assignees: [ rye ]
  allow:
  - dependency-type: direct
  - dependency-type: indirect
