branch: true
llvm: true
output-type: lcov
output-path: ./lcov.info
prefix-dir: /home/runner/work/distringo/distringo/

binary-path: /home/runner/work/distringo/distringo/target/debug/

ignore:
- "/*"
- "C:/*"
- "../*"
