[package]
name = "distringo"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
config = { version = "0.11.0", default_features = false, features = ["json", "yaml"] }
csv = "1.1.6"
fnv = "1.0.7"
futures = { version = "0.3" }
geo = "0.18.0"
geojson = "0.22.2"
http = "0.2.6"
hyper = "0.14.16"
log = "0.4.14"
lazy_static = "1.4.0"
once_cell = "1.8.0"
pretty_env_logger = "0.4.0"
regex = "1.5.4"
serde = { version = "1.0.135", features = ["derive"] }
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.8", default_features = false }
warp = { version = "0.3.2", features = ["compression"] }

[dev-dependencies]
criterion = "0.3.5"
simple_logger = "1.15.0"
serde_yaml = "0.8.21"

[[bench]]
name = "logical_record_position_index"
path = "benches/index/logical_record_position.rs"
harness = false

[workspace]
members = [
	"palapelify",
]
