[package]
name = "distringo-census-datalink"
version = "0.1.0"
edition = "2021"

[features]
default = ["census-ftp"]
census-ftp = ["dep:suppaftp"]

[dependencies]
suppaftp = { version = "5.2.0", optional = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
