[package]
name = "server"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
config = { version = "~0.10.1", default_features = false, features = ["json", "yaml"] }
csv = "~1.1.3"
fnv = "~1.0.7"
geo = "~0.13.0"
geojson = "~0.18.0"
http = "~0.2.1"
hyper = "~0.13.6"
log = "~0.4.8"
pretty_env_logger = "~0.4.0"
tokio = { version = "~0.2.21", features = ["macros"] }
warp = { version = "~0.2.3", features = ["compression"] }
lazy_static = "~1.4.0"
regex = "~1.3.9"
serde = { version = "~1.0.111", features = ["derive"] }
distringo = { path = ".." }

[dev-dependencies]
criterion = "~0.3.2"
simple_logger = "~1.6.0"
serde_yaml = "~0.8.12"
