[package]
name = "palapelify"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.1.5"
geo = "0.19.0"
geojson = { version = "0.22.0", features = ["geo-types"] }
geo-types = "0.7.0"
itertools = "0.10.3"
num-traits = "0.2.14"
rayon = "1.5.1"
serde_json = "1.0.78"
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
